### ISSUE TITLE
Regex in dotmarketing-config.properties file being mangled by templating process

### ISSUE THREAD

**Issue by brentgriffin** [dotCMS/docker#7]
This value is being modified during the templating process:
```
##Static Push Bucket Name Restrictions
STATIC_PUSH_BUCKET_NAME_REGEX=[,!:;&?$\\\\*\\/\\[\\]=\\|#_@\\(\\)<>\\s\\+"]+
```
Result is that static push to s3 fails because the regex statement is not valid

Logs from attempted push:
```
13:26:43.787  INFO  publishing.PublisherAPIImpl - Start of Bundler: c
13:26:43.831  INFO  publishing.PublisherAPIImpl - End of Bundler: c
13:26:43.831  INFO  publishing.PublisherAPIImpl - Start of Bundler: FileAssetBundler
13:26:43.832  INFO  bundlers.FileAssetBundler - +structuretype:4 +(path:/quest-logo.svg ) +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797  )
13:26:43.870  ERROR staticpublishing.AWSS3Publisher - Unclosed character class near index 26
[,!:;&?$\*/[]=|#_@()<>s+"]+
                          ^
java.util.regex.PatternSyntaxException: Unclosed character class near index 26
[,!:;&?$\*/[]=|#_@()<>s+"]+
                          ^
    at java.util.regex.Pattern.error(Pattern.java:1957) ~[?:1.8.0_212]
    at java.util.regex.Pattern.clazz(Pattern.java:2550) ~[?:1.8.0_212]
    at java.util.regex.Pattern.sequence(Pattern.java:2065) ~[?:1.8.0_212]
    at java.util.regex.Pattern.expr(Pattern.java:1998) ~[?:1.8.0_212]
    at java.util.regex.Pattern.compile(Pattern.java:1698) ~[?:1.8.0_212]
    at java.util.regex.Pattern.<init>(Pattern.java:1351) ~[?:1.8.0_212]
    at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_212]
    at java.lang.String.replaceAll(String.java:2223) ~[?:1.8.0_212]
    at com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher.a(SourceFile:453) ~[ee-5.1.5.jar:?]
    at com.dotcms.enterprise.publishing.staticpublishing.AWSS3Publisher.a(SourceFile
```

**Comment by wezell** [comment]
You can comment out the property as the default is now set in code.

**Comment by brentgriffin** [comment]
Verified fix in openshiftchanges branch
